package Test;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author TribalRope
 */
public class FinsertarCliente extends javax.swing.JFrame {

    static Connection conn = null;

    /**
     * Creates new form FinsertarCliente
     */
    public FinsertarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIDCLIENTE = new javax.swing.JLabel();
        jLabelNOMBRE = new javax.swing.JLabel();
        jLabelAPELLIDO = new javax.swing.JLabel();
        jLabelEMAIL = new javax.swing.JLabel();
        jTextIDCLIENTE = new javax.swing.JTextField();
        jTextNOMBRECLIENTE = new javax.swing.JTextField();
        jTextAPELLIDOCLIENTE = new javax.swing.JTextField();
        jTextCORREO = new javax.swing.JTextField();
        jButtonINSERTAR = new javax.swing.JButton();
        jButtonMOSTRAR = new javax.swing.JButton();
        jLabelCEDULA = new javax.swing.JLabel();
        jLabelTELEFONO = new javax.swing.JLabel();
        jTextCEDULA = new javax.swing.JTextField();
        jTextTELEFONO = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelIDCLIENTE.setText("ID Cliente:");

        jLabelNOMBRE.setText("Nombre:");

        jLabelAPELLIDO.setText("Apellido:");

        jLabelEMAIL.setText("Email:");

        jTextIDCLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIDCLIENTEActionPerformed(evt);
            }
        });

        jTextAPELLIDOCLIENTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAPELLIDOCLIENTEActionPerformed(evt);
            }
        });

        jButtonINSERTAR.setText("Insertar Cliente");
        jButtonINSERTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonINSERTARActionPerformed(evt);
            }
        });

        jButtonMOSTRAR.setText("Mostrar Cliente");
        jButtonMOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMOSTRARActionPerformed(evt);
            }
        });

        jLabelCEDULA.setText("Cédula:");

        jLabelTELEFONO.setText("Teléfono:");

        jTextCEDULA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCEDULAActionPerformed(evt);
            }
        });

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIDCLIENTE)
                            .addComponent(jLabelNOMBRE)
                            .addComponent(jLabelAPELLIDO)
                            .addComponent(jLabelEMAIL)
                            .addComponent(jLabelCEDULA)
                            .addComponent(jLabelTELEFONO)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonINSERTAR)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMOSTRAR))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextTELEFONO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addComponent(jTextCEDULA, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextNOMBRECLIENTE, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextAPELLIDOCLIENTE, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextCORREO, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextIDCLIENTE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIDCLIENTE)
                    .addComponent(jTextIDCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNOMBRE)
                    .addComponent(jTextNOMBRECLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAPELLIDO)
                    .addComponent(jTextAPELLIDOCLIENTE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCEDULA)
                    .addComponent(jTextCEDULA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTELEFONO)
                    .addComponent(jTextTELEFONO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEMAIL)
                    .addComponent(jTextCORREO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonINSERTAR)
                    .addComponent(jButtonMOSTRAR))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonINSERTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonINSERTARActionPerformed
        // TODO add your handling code here:
        try {
            // main miconexion = new main();
            conn = DatabaseUtils.Enlace(conn);
            String sqlinsertar = "BEGIN\n"
                    + "   inCli(?,?,?,?,?,?);\n"
                    + "END;";
            PreparedStatement psta = conn.prepareStatement(sqlinsertar);
            psta.setString(1, jTextIDCLIENTE.getText());
            psta.setString(2, jTextNOMBRECLIENTE.getText());
            psta.setString(3, jTextAPELLIDOCLIENTE.getText());
            psta.setString(4, jTextTELEFONO.getText());
            psta.setString(5, jTextCEDULA.getText());
            psta.setString(6, jTextCORREO.getText());
            psta.execute();
            psta.close();
            JOptionPane.showMessageDialog(null, "Registro Guardado Exitosamente");
        } catch (Exception e) {
            System.out.println(e.getCause());
        }
        limpiar();


    }//GEN-LAST:event_jButtonINSERTARActionPerformed

    public void limpiar() {
        jTextIDCLIENTE.setText("");
        jTextNOMBRECLIENTE.setText("");
        jTextAPELLIDOCLIENTE.setText("");
        jTextCORREO.setText("");
        jTextCEDULA.setText("");
        jTextTELEFONO.setText("");
    }

    private void jTextIDCLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIDCLIENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIDCLIENTEActionPerformed

    private void jTextAPELLIDOCLIENTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAPELLIDOCLIENTEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAPELLIDOCLIENTEActionPerformed

    private void jButtonMOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMOSTRARActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FMostrarCliente Fmostrar = new FMostrarCliente();
        Fmostrar.setVisible(true);
        Fmostrar.pack();

    }//GEN-LAST:event_jButtonMOSTRARActionPerformed

    private void jTextCEDULAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCEDULAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCEDULAActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Menu menu=new Menu();
menu.setVisible(true);
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinsertarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinsertarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinsertarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinsertarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinsertarCliente().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonINSERTAR;
    private javax.swing.JButton jButtonMOSTRAR;
    private javax.swing.JLabel jLabelAPELLIDO;
    private javax.swing.JLabel jLabelCEDULA;
    private javax.swing.JLabel jLabelEMAIL;
    private javax.swing.JLabel jLabelIDCLIENTE;
    private javax.swing.JLabel jLabelNOMBRE;
    private javax.swing.JLabel jLabelTELEFONO;
    private javax.swing.JTextField jTextAPELLIDOCLIENTE;
    private javax.swing.JTextField jTextCEDULA;
    private javax.swing.JTextField jTextCORREO;
    private javax.swing.JTextField jTextIDCLIENTE;
    private javax.swing.JTextField jTextNOMBRECLIENTE;
    private javax.swing.JTextField jTextTELEFONO;
    // End of variables declaration//GEN-END:variables
}
