package Test;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TribalRope
 */
public class FinsertarPlanta extends javax.swing.JFrame {

    static Connection conn = null;

    /**
     * Creates new form FinsertarCliente
     */
    public FinsertarPlanta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelIdPlanta = new javax.swing.JLabel();
        jLabelNombrePlanta = new javax.swing.JLabel();
        jLabelNombreCientifico = new javax.swing.JLabel();
        jLabelPrecioPlanta = new javax.swing.JLabel();
        jTextIdPlanta = new javax.swing.JTextField();
        jTextNombrePlanta = new javax.swing.JTextField();
        jTextNombreCientifico = new javax.swing.JTextField();
        jTextPrecioPlanta = new javax.swing.JTextField();
        jButtonInsertarPlanta = new javax.swing.JButton();
        jButtonMostrarPlanta = new javax.swing.JButton();
        jLabelDescripcionPlanta = new javax.swing.JLabel();
        jLabelToxicidadPlanta = new javax.swing.JLabel();
        jTextDescripcionPlanta = new javax.swing.JTextField();
        jTextToxicidad = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelIdPlanta.setText("ID Planta:");

        jLabelNombrePlanta.setText("Nombre Común:");

        jLabelNombreCientifico.setText("Nombre Científico :");

        jLabelPrecioPlanta.setText("Precio:");

        jTextIdPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdPlantaActionPerformed(evt);
            }
        });

        jTextNombreCientifico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreCientificoActionPerformed(evt);
            }
        });

        jButtonInsertarPlanta.setText("Insertar Planta");
        jButtonInsertarPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarPlantaActionPerformed(evt);
            }
        });

        jButtonMostrarPlanta.setText("Mostrar Cliente");
        jButtonMostrarPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarPlantaActionPerformed(evt);
            }
        });

        jLabelDescripcionPlanta.setText("Descripción:");

        jLabelToxicidadPlanta.setText("Toxicidad:");

        jTextDescripcionPlanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDescripcionPlantaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIdPlanta)
                    .addComponent(jLabelNombrePlanta)
                    .addComponent(jLabelNombreCientifico)
                    .addComponent(jLabelPrecioPlanta)
                    .addComponent(jLabelDescripcionPlanta)
                    .addComponent(jLabelToxicidadPlanta))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInsertarPlanta)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMostrarPlanta))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jTextToxicidad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                        .addComponent(jTextDescripcionPlanta, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextNombrePlanta, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextNombreCientifico, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextPrecioPlanta, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTextIdPlanta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelIdPlanta)
                    .addComponent(jTextIdPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombrePlanta)
                    .addComponent(jTextNombrePlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNombreCientifico)
                    .addComponent(jTextNombreCientifico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDescripcionPlanta)
                    .addComponent(jTextDescripcionPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelToxicidadPlanta)
                    .addComponent(jTextToxicidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrecioPlanta)
                    .addComponent(jTextPrecioPlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonInsertarPlanta)
                    .addComponent(jButtonMostrarPlanta))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonInsertarPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarPlantaActionPerformed
        // TODO add your handling code here:
        try {
            // main miconexion = new main();
            conn = main.Enlace(conn);
            String sqlinsertar = "BEGIN\n"
                    + "   inCli(?,?,?,?,?,?);\n"
                    + "END;";
            PreparedStatement psta = conn.prepareStatement(sqlinsertar);
            psta.setString(1, jTextIdPlanta.getText());
            psta.setString(2, jTextNombrePlanta.getText());
            psta.setString(3, jTextNombreCientifico.getText());
            psta.setString(4, jTextToxicidad.getText());
            psta.setString(5, jTextDescripcionPlanta.getText());
            psta.setString(6, jTextPrecioPlanta.getText());
            psta.execute();
            psta.close();
            JOptionPane.showMessageDialog(null, "Registro Guardado Exitosamente");
        } catch (Exception e) {
            System.out.println(e.getCause());
        }
        limpiar();


    }//GEN-LAST:event_jButtonInsertarPlantaActionPerformed

    public void limpiar() {
        jTextIdPlanta.setText("");
        jTextNombrePlanta.setText("");
        jTextNombreCientifico.setText("");
        jTextPrecioPlanta.setText("");
        jTextDescripcionPlanta.setText("");
        jTextToxicidad.setText("");
    }

    private void jTextIdPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdPlantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdPlantaActionPerformed

    private void jTextNombreCientificoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreCientificoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreCientificoActionPerformed

    private void jButtonMostrarPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarPlantaActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        FMostrarPlanta Fmostrar = new FMostrarPlanta();
        Fmostrar.setVisible(true);
        Fmostrar.pack();

    }//GEN-LAST:event_jButtonMostrarPlantaActionPerformed

    private void jTextDescripcionPlantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDescripcionPlantaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDescripcionPlantaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinsertarPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinsertarPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinsertarPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinsertarPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinsertarPlanta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInsertarPlanta;
    private javax.swing.JButton jButtonMostrarPlanta;
    private javax.swing.JLabel jLabelDescripcionPlanta;
    private javax.swing.JLabel jLabelIdPlanta;
    private javax.swing.JLabel jLabelNombreCientifico;
    private javax.swing.JLabel jLabelNombrePlanta;
    private javax.swing.JLabel jLabelPrecioPlanta;
    private javax.swing.JLabel jLabelToxicidadPlanta;
    private javax.swing.JTextField jTextDescripcionPlanta;
    private javax.swing.JTextField jTextIdPlanta;
    private javax.swing.JTextField jTextNombreCientifico;
    private javax.swing.JTextField jTextNombrePlanta;
    private javax.swing.JTextField jTextPrecioPlanta;
    private javax.swing.JTextField jTextToxicidad;
    // End of variables declaration//GEN-END:variables
}
